title: Anthony Stark
logo: "/images/IMG_0891resized.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst | Former STEM Educator
  <br><br>
  Skills:
  <br>
   - Microsoft Excel
  <br>
   - Tableau
  <br>
   - SQL
  <br>
   - Python
  <br><br>
  <a href="https://www.linkedin.com/in/amstark22/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-SFK59CG41P # your Google Analytics tracking ID here

